github:
  prebuilds:
    master: false
    branches: false
tasks:
  - name: deploy
    init: docker pull oceanbase/oceanbase-ce
    command: | 
          docker run -p 2881:2881 --name obstandalone -e MINI_MODE=1 -d oceanbase/oceanbase-ce
          bash /workspace/ob-example/python/py_env.sh
          bash /workspace/ob-example/tools/scripts/gitpod.sh
  - name: DB Server
    command: |
          echo "alias example='bash /workspace/ob-example/example.sh' " >> ~/.profile
          bash /workspace/ob-example/go/go_env.sh
          bash /workspace/ob-example/java/java_env.sh
          source ~/.profile
          clear
          echo -e "$(< ./tools/scripts/gitpod_welcome)"
          cd /workspace/ob-example
    openMode: split-right
